modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
authors = "${mod_authors}"
description = "${mod_description}"
logoFile = "${mod_logo}"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_target_version},)"

[[dependencies.${mod_id}]]
modId = "minecraft"
versionRange = "[${minecraft_version}]"

[[dependencies.${mod_id}]]
modId = "cobblemon"
versionRange = "[${cobblemon_target_version},)"

